"use client";

import { useEffect } from "react";
import { useParams, useRouter } from "next/navigation";

import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Separator } from "@/components/ui/separator";
import { Sparkles, FileText, AlertCircle, FileSearch, Trash2 } from "lucide-react";
import { MarkDown } from "@/components/common/react-markdown";
import { Button } from "@/components/ui/button";
import { Alert as AlertDialog } from "@/components/common/alert";
import { toast } from "sonner";
import { useSummaryStore } from "@/store/useSummaryStore";

export default function SummarizePage() {
  const params = useParams();
  const id = params?.id as string;
  const router = useRouter();

  const {
    summary,
    isSummaryLoading,
    summaryError,
    fetchSummary,
    deleteSummary
  } = useSummaryStore();

  useEffect(() => {
    if (id) {
      fetchSummary(id);
    }
  }, [id, fetchSummary]);

  return (
    <div className="p-4">
      <div className="space-y-4 pb-6">
        <div className="flex items-center justify-between gap-5">
          <div className="flex flex-col gap-2">
            <div className="flex items-center gap-2">
              <div className="p-1.5 rounded-lg bg-accent border">
                <FileSearch className="h-5 w-5 sm:h-6 sm:w-6 text-primary" />
              </div>
              <h1 className="text-2xl sm:text-3xl font-bold">Document Summary</h1>
            </div>
            <p className="sm:text-lg ms-2">
              A detailed breakdown of the key concepts and arguments found in your PDF.
            </p>
          </div>
          <AlertDialog
            trigger={
              <Button size="sm">
                <Trash2 />
                <span className="hidden sm:inline">Delete Summary</span>
              </Button>
            }
            title={`Delete ${summary?.title} Summary?`}
            description="This action will remove this summary permanently. You won't be able to recover it."
            onContinue={() => deleteSummary(id, () => {
              toast.success("Summary deleted successfully");
              router.push("/summarize");
            })}
          />
        </div>
      </div>

      <Card className="max-w-4xl mx-auto mt-5 shadow-lg border-border bg-card">
        <CardHeader className="space-y-1">
          <div className="flex items-center gap-2 text-primary">
            <div className="p-2 bg-primary/10 rounded-full">
              <Sparkles className="h-5 w-5" />
            </div>
            <span className="font-semibold tracking-wide uppercase text-sm">AI Generated Analysis</span>
          </div>
          <CardTitle className="text-2xl sm:text-3xl font-semibold">{summary?.title}</CardTitle>
          <CardDescription className="sm:text-lg">
            A detailed breakdown of the key concepts and arguments found in your PDF.
          </CardDescription>
        </CardHeader>

        <Separator />

        <CardContent>
          {summaryError ? (
            <Alert variant="destructive">
              <AlertCircle className="h-4 w-4" />
              <AlertTitle>Error</AlertTitle>
              <AlertDescription>{summaryError}</AlertDescription>
            </Alert>
          ) : isSummaryLoading ? (
            <div className="space-y-6">
              <div className="space-y-2">
                <Skeleton className="h-4 w-3/4" />
                <Skeleton className="h-4 w-full" />
                <Skeleton className="h-4 w-5/6" />
              </div>
              <div className="space-y-2">
                <Skeleton className="h-4 w-full" />
                <Skeleton className="h-4 w-4/5" />
                <Skeleton className="h-4 w-full" />
              </div>
              <div className="h-32 w-full bg-muted/20 rounded-md animate-pulse" />
            </div>
          ) : (
            <div className="prose prose-slate dark:prose-invert max-w-none 
              prose-headings:font-bold prose-h3:text-xl prose-h3:mt-6 prose-h3:mb-3
              prose-p:leading-relaxed prose-p:text-muted-foreground prose-p:mb-4
              prose-strong:text-foreground prose-strong:font-semibold
              prose-ul:my-4 prose-li:my-1
            ">
              <MarkDown content={summary?.content} />
            </div>
          )}
        </CardContent>
      </Card>

      {!isSummaryLoading && !summaryError && (
        <div className="mt-5 flex justify-center text-muted-foreground text-sm items-center gap-2">
          <FileText className="h-4 w-4 opacity-50" />
          <p>Generated by Gemini 1.5 Flash</p>
        </div>
      )}
    </div>
  );
}